config/routes.rb
RentMyBike::Application.routes.draw do
  devise_for :users

  resources :listings, :rentals

  root 'listings#index'

end

app/models/listing.rb
class Listing < ActiveRecord::Base
  belongs_to :user
  has_many :rentals

  attr_accessible :name, :user_id, :location, :title, :description, :bicycle_type, :price

  def rent(params = {})
    renter = params[:renter]
    user = params[:user] || User.find_by(customer_href: renter.href)
    user_id = user.nil? ? nil : user.id

    # TODO: if a renter already has a valid card, then, use that to charge
    # otherwise, the card_href should be used as the source

    card = Balanced::Card.fetch(params[:card_href])
    card.associate_to_customer(renter)

    # create an Order
    order = self.user.balanced_customer.create_order(
      description: self.description
    )

    # debit the buyer for the amount of the listing
    order.debit_from(
      source: card,
      amount: self.price,
      description: self.description,
      appears_on_statement_as: 'RentMyBike Rental'
    )

    # credit the owner of bicycle for the amount of listing
    # 
    # since this is an example, we're showing how to issue a credit
    # immediately. normally you should wait for order fulfillment
    # before crediting.

    order.credit_to(
      destination: self.user.balanced_bank_account,
      amount: self.price,
      description: self.description,
      appears_on_statement_as: 'RMyBike Payout'
    )

    rental = Rental.new(
      listing_id: self.id,
      buyer_id: user_id,
      owner_id: self.user.id,
      order_href: order.href
    )
    rental.save
  end
end

app/models/rental.rb
class Rental < ActiveRecord::Base
  belongs_to :buyer, :class_name => 'User'
  belongs_to :owner, :class_name => 'User'
  belongs_to :listing

  attr_accessible :buyer_id, :owner_id, :listing_id, :order_href
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me,
    :name, :customer_href, :bank_account_href

  has_many :owner_rentals, :class_name => 'Rental', :foreign_key => 'owner_id'
  has_many :buyer_rentals, :class_name => 'Rental', :foreign_key => 'buyer_id'

  has_many :listings

  def balanced_bank_account
    return Balanced::Customer.fetch(self.bank_account_href) if self.bank_account_href
  end
  
  def balanced_customer
    return Balanced::Customer.fetch(self.customer_href) if self.customer_href

    begin
      customer = self.class.create_balanced_customer(
        :name   => self.name,
        :email  => self.email
        )
    rescue
      'There was error fetching the Balanced customer'
    end

    self.customer_href = customer.href
    self.save

    customer
  end

  def self.create_balanced_customer(params = {})
    begin
      Balanced::Customer.new(
        :name   => params[:name],
        :email  => params[:email]
      ).save
    rescue
      'There was an error adding a customer'
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_filter :authenticate_user!, :only => [:new, :create, :edit, :update]
  before_filter :listing_owner_required, :only => [:edit, :update]

  def index
    @listings = Listing.all
  end

  def show
    @listing = Listing.find(params[:id])
  end

  def create
    owner_customer = current_user.balanced_customer
    bank_account_href = params[:bank_account_href]

    # add bank account href passed back from balanced.js
    bank_account = Balanced::BankAccount.fetch(bank_account_href)
    bank_account.associate_to_customer(owner_customer)
    current_user.bank_account_href = bank_account.href
    current_user.save

    @listing = current_user.listings.new(
      title: params[:listing_title],
      location: params[:listing_location],
      bicycle_type: params[:listing_bike_type],
      price: params[:listing_rent_price].to_i * 100
    )

    if @listing.save!
      render :confirmation
    else
      render :new
    end
  end

  def new
    @random_listing = Listing.find(rand(Listing.all.length)+1)
  end

  def edit
    @listing = current_user.listings.find(params[:id])
  end

  def update
    @listing = current_user.listings.find(params[:id])
    if @listing.update_attributes(params[:listing])
      @listing.price = @listing.price * 100
      @listing.save!
      flash[:notice] = "Listing updated successfully."
      redirect_to listing_path(@listing)
    else
      flash[:error] = "There was a problem updating the listing."
      render :action => :edit
    end
  end

private

  def listing_owner_required
    head :forbidden unless (@listing.present? && user_signed_in? && @listing.users.include?(current_user))
  end

end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController

  def create
    # user represents a user in our database who wants to rent a bicycle
    # buyer is a Balanced::Customer object that knows about payment information for user
    # or guest who wants to rent a bicycle

    buyer, user = nil, nil

    # logic to handle guest/not signed in users

    if user_signed_in?
      buyer = current_user.balanced_customer
    else
      buyer = User.create_balanced_customer(
        :name  => params[:"guest-name"],
        :email => params[:"guest-email_address"]
      )
    end

    listing = Listing.find(params[:listing_id])
    listing.rent(renter: buyer, card_href: params[:card_href])
    render :confirmation
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rentals_helper.rb
module RentalsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RentMyBike</title>
  <script type="text/javascript" src="https://js.balancedpayments.com/1.1/balanced.js"></script>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
    <header>
        <div class="minor">
            <nav>
            <% if user_signed_in? %>
                <li><%= current_user.email %></li>
                <li><%= link_to('Edit Account', edit_user_registration_path(current_user)) %></li>
                <li><%= link_to('Log out', destroy_user_session_path) %></li>
            <% else %>
                <li><%= link_to('log in', new_user_session_path) %></li>
                <li><%= link_to('sign up', new_user_registration_path) %></li>
            <% end %>
            </nav>
        </div>
        <div class="major">
            <h1><a href="/">Rent My Bike</a></h1>
            <nav>
                <li class="selected"><a href="/">Rent a Bike</a></li>
                <li><%= link_to('list a bike', new_listing_path) %></li>
            </nav>
        </div>
    </header>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
<section id="main">
    <%= yield %>
</section>
<footer>
    <div>
	   <p>Copyright &copy; 2013. <a href="https://www.balancedpayments.com/">Balanced</a>.</p>
	</div>
</footer>
    <a href="https://github.com/balanced/rentmybikes-rails" id="github">
    	<img src="https://s3.amazonaws.com/github/ribbons/forkme_left_darkblue_121621.png" alt="Fork me on GitHub">
    </a>
    <iframe src="https://js.balancedpayments.com/proxy#https%3A%2F%2Fwww.rentmybike.co%2Frent%2F1" name="balancedFrame1369164291198" id="balancedFrame1369164291198" frameborder="0" scrolling="no" allowtransparency="true" width="0" height="0" style="position:absolute;top:0;left:0;width:0;height:0"></iframe>
</body>
</html>

app/views/listings/_checkout.html.erb
<div class="row">
    <div class="span7 box">
        <h1>Checkout</h1>
        <div class="span6 offset1">
            <%= form_tag({:controller => 'rentals', :action => 'create', :method => 'post'}, {:id => 'purchase'}) do %>
            <%= hidden_field_tag(:"guest-name", user.name) %>
            <%= hidden_field_tag(:"guest-email_address", user.email) %>
            <div>
              <label>Name on Card</label>
              <input type="text" id="guest-name" name="guest-name" autocomplete="off" />
            </div>
            <div>
              <label>Card Number</label>
              <input type="text" id="guest-number" name="guest-number" autocomplete="off" maxlength="16" />
            </div>
            <div>
              <label>Expiration</label>
              <%= select_tag(:"guest-expiration_month", options_for_select(1.upto(12).map{ |num| [num,num] }), :class => 'span1', :id => 'guest-expiration_month') %>
              <%= select_tag(:"guest-expiration_year", options_for_select(Time.now.year.upto(Time.now.year+10).map{ |num| [num,num] }), :class => 'span1', :id => 'guest-expiration_year') %>
            </div>
            <div>
              <label>Card Verification Code (CVV)</label>
              <input type="text" id="guest-cvv" name="guest-cvv" class="span1" autocomplete="off" maxlength="4" />
            </div>
            <div>
              <label>Postal Code</label>
              <input type="text" id="guest-postal_code" name="guest-postal_code" class="span1" autocomplete="off" />
            </div>
            <%= hidden_field_tag(:listing_id, @listing.id) %>
            <div>
                <%= submit_tag 'Rent', class: 'btn-primary' %>
            </div>
            <% end %>
            <a href="https://www.balancedpayments.com"><img src="https://balancedpowered.s3.amazonaws.com/secured-1-1.png" alt="Secured by Balanced"></a>
        </div>
    </div>
</div>

app/views/listings/_guest_checkout.html.erb
<div class="row">
    <div class="span7 box">
        <h1>Checkout</h1>
        <div class="span6 offset1">
            <%= form_tag({:controller => 'rentals', :action => 'create', :method => 'post'}, {:id => 'purchase'}) do %>
            <p>
              I already have an account.
              <%= link_to('Sign me in', user_session_path) %>
            </p>
            <div>
              <label>Name on Card</label>
              <input type="text" id="guest-name" name="guest-name" autocomplete="off" />
            </div>
            <div>
              <label>Card Number</label>
              <input type="text" id="guest-number" name="guest-number" autocomplete="off" maxlength="16" />
            </div>
            <div>
              <label>Expiration</label>
              <%= select_tag(:"guest-expiration_month", options_for_select(1.upto(12).map{ |num| [num,num] }), :class => 'span1', :id => 'guest-expiration_month') %>
              <%= select_tag(:"guest-expiration_year", options_for_select(Time.now.year.upto(Time.now.year+10).map{ |num| [num,num] }), :class => 'span1', :id => 'guest-expiration_year') %>
            </div>
            <div>
              <label>Card Verification Code (CVV)</label>
              <input type="text" id="guest-cvv" name="guest-cvv" class="span1" autocomplete="off" maxlength="4" />
            </div>
            <div>
              <label>Postal Code</label>
              <input type="text" id="guest-postal_code" name="guest-postal_code" class="span1" autocomplete="off" />
            </div>
            <div>
              <%= label_tag(:"guest-email_address", 'Email', :class => 'control-label') %>
              <%= text_field_tag(:"guest-email_address", nil,  :class => 'span5', :id => 'guest-email_address') %>
            </div>
            <%= hidden_field_tag(:listing_id, @listing.id) %>
            <div>
              <%= submit_tag 'Rent', class: 'btn-primary' %>
            </div>
            <% end %>
            <a href="https://www.balancedpayments.com"><img src="https://balancedpowered.s3.amazonaws.com/secured-1-1.png" alt="Secured by Balanced"></a>
        </div>
    </div>
</div>

app/views/listings/_listing.html.erb
<div class="box bike <%= listing.bicycle_type %>">
    <div class="title">
        <h2><%= listing.title %></h2>
    </div>
    <div class="body">
        <div class="description">
            <p><%= listing.description %></p>
            <div class="price">
                <span><%= listing.price ? listing.price/100 : 10 %></span>
                per day
            </div>
        </div>
        <div class="info">
            <div>
                <strong>Location</strong>
                <span><%= listing.location %></span>
            </div>
            <div>
                <strong>Type</strong>
                <span><%= listing.bicycle_type %></span>
            </div>
            <div>
                <% if user_signed_in? && current_user.listings.include?(listing) %>
                    <%= link_to('Edit this listing', edit_listing_path(listing),:class => 'btn')  %>                   
                <% end %>
            	<%= link_to('Rent this bike', listing_path(listing),:class => 'btn btn-inverse')  %>
            </div>
        </div>
    </div>
</div>

app/views/listings/_new_listing.html.erb
<%= render :partial => 'listing', :locals => { :listing => @random_listing} %>
<div class="row">
    <div class="span7 box">
        <h1>List your bike</h1>
        <div class="span6">
            <%= form_tag({:controller => 'listings', :action => 'create', :method => 'post'},{:id => 'kyc'}) do %>
            
            <%= hidden_field_tag(:"guest-email_address", user.email) %>
            
            <fieldset>
              <div>
                  <%= label_tag(:listing_title, 'Listing Title', :class => 'control-label') %>
                  <%= text_field_tag(:listing_title, nil, :placeholder => @random_listing.title, :class => 'span5', :id => 'listing-title') %>
              </div>
              <div>
                  <%= label_tag(:listing_description, 'Listing Description', :class => 'control-label') %>
                  <%= text_area_tag(:listing_description, nil, :placeholder => @random_listing.description, :class => 'span5', :id => 'listing-description') %>
              </div>
              <div>
                  <%= label_tag(:listing_location, 'Location', :class => 'control-label') %>
                  <%= text_field_tag(:listing_location, nil, :placeholder => @random_listing.location, :class => 'span5', :id => 'listing-location') %>
              </div>
              <div>
                  <%= label_tag(:listing_bike_type, 'Bike Type', :class => 'control-label') %>
                  <%= select_tag(:listing_bike_type, options_for_select(["fixie", "hybrid", "road", "touring"]), :class => 'span3', :id => 'listing-bike-type') %>
              </div>
              <div>
                  <%= label_tag(:listing_rent_price, 'Rental Price (in Dollars)', :class => 'control-label') %>
                  <%= text_field_tag(:listing_rent_price, nil, :placeholder => @random_listing.price/100, :class => 'span1', :id => 'listing-rent-price') %>
              </div>
              <div>
                  <%= label_tag(:"guest-street_address", 'Home Address', :class => 'control-label') %>
                  <%= text_field_tag(:"guest-street_address", nil,  :class => 'span5', :id => 'guest-street_address') %>
              </div>
              <div>
                  <%= label_tag(:"guest-postal_code", 'Zip Code') %>
                  <%= text_field_tag(:"guest-postal_code", nil,  :class => 'span2', :id => 'guest-postal_code') %>
              </div>
              <%= hidden_field_tag(:"guest-state", nil, :id => 'guest-state') %>
              <%= hidden_field_tag(:"guest-country_code", 'USA', :id => 'guest-country_code') %>
              <div>
                  <%= label_tag(:"guest-phone_number", 'Phone Number') %>
                  <%= text_field_tag(:"guest-phone_number", nil, :class => 'span2', :id => 'guest-phone_number') %>
              </div>
              <div>
                  <%= label_tag(:date_of_birth_month, 'Date of Birth') %>
                  <%= select_tag(:"guest-date_of_birth_month", options_for_select(1.upto(12).map{ |num| [num,num] }), :class => 'span1', :id => 'guest-date_of_birth_month') %>
                  <%= select_tag(:"guest-date_of_birth_year", options_for_select(1900.upto(Time.now.year - 18).map{ |num| [num,num] }), :class => 'span1', :id => 'guest-date_of_birth_year') %>
              </div>
            </fieldset>
            
            <br>
            
            <fieldset>
                <legend>
                    Add your bank account
                    <span>(optional)</span>
                </legend>
                <div>
                    <%= label_tag(:name, 'Account Holder\'s Name') %>
                    <%= text_field_tag(:name, nil, :id => 'name') %>
                    <span id="name-result"></span>
                </div>
                <div>
                    <%= label_tag(:routing_number, 'Routing Number') %>
                    <%= text_field_tag(:routing_number, nil, :id => 'routing_number') %>
                    <span id="routing-number-result"></span>
                </div>
                <div>
                    <%= label_tag(:account_number, 'Account Number', :class => 'control-label') %>
                    <div class="controls">
                        <%= text_field_tag(:account_number, nil, :id => 'account_number') %>
                    </div>
                </div>
                <div>
                    <%= label_tag(:account_type, 'Account Type') %>
                    <%= select_tag(:account_type, options_for_select(['Checking', 'Savings'].map{ |t| [t, t.downcase] }), :class => 'span2', :id => 'account_type') %>
                </div>
            </fieldset>
            <div class="actions">
                <%= submit_tag 'Save', class: 'btn-primary' %>
            </div>
            
            <% end %>
        </div>
    </div>
</div>

app/views/listings/confirmation.html.erb
<div class="row">
    <div class="span7 box">
        <h1>You have successfully listed an item!</h1>
        <div class="swell">
            <p>Rentmybike is a demo marketplace for Balanced. You are now able
                to sell on any marketplace powered by Balanced.</p>
            <p>Start integrating payments by visiting
                <a href="https://www.balancedpayments.com">balancedpayments.com</a></p>
        </div>
    </div>
</div>

app/views/listings/edit.html.erb
<%= render :partial => 'listing', :locals => { :listing => @listing} %>
<div class="row">
    <div class="span7 box">
        <h1>List your bike</h1>
        <div class="span6 offset1">
            <%= form_for @listing do |f| %>
                <%= f.label(:title, 'Listing Title', :class => 'control-label') %>
                <%= f.text_field(:title, :class => 'span5', :id => 'listing-title') %>
                <%= f.label(:description, 'Listing Description', :class => 'control-label') %>
                <%= f.text_area(:description, :class => 'span5', :id => 'listing-description') %>
                <%= f.label(:location, 'Location', :class => 'control-label') %>
                <%= f.text_field(:location, :class => 'span5', :id => 'listing-location') %>
                <%= f.label(:bicycle_type, 'Bike Type', :class => 'control-label') %>
                <%= f.select(:bicycle_type, options_for_select(["fixie", "hybrid", "road", "touring"]), :class => 'span5', :id => 'listing-bike-type') %>
                <%= f.label(:price, 'Rental Price (in Dollars)', :class => 'control-label') %>
                <%= f.text_field(:price, :value => (f.object.price.to_i)/100, :class => 'span5', :id => 'listing-rent-price') %>
                <%= f.submit("Update Listing") %>
            <% end %>
        </div>
    </div>
</div>

app/views/listings/index.html.erb
<% @listings.each do |listing| %>
    <%= render :partial => 'listing', :locals => { :listing => listing } %>
<% end %>

app/views/listings/new.html.erb
<%= render :partial => 'new_listing', :locals => { :user => current_user } %>

app/views/listings/show.html.erb
<%= render :partial => 'listing', :locals => { :listing => @listing } %>
<% if user_signed_in? %>
	<%= render :partial => 'checkout', :locals => { :listing => @listing, :user => current_user } %>
<% else %>
	<%= render :partial => 'guest_checkout', :locals => { :listing => @listing } %>
<% end %>

app/views/rentals/confirmation.html.erb
<div class="row">
    <div class="span7 box">
        <h1>You have successfully confirmed a rental</h1>
        <div class="swell">
            <p>Rentmybike is a demo marketplace for Balanced. You are now able
                to sell on any marketplace powered by Balanced.</p>
            <p>Start integrating payments by visiting
                <a href="https://www.balancedpayments.com">balancedpayments.com</a></p>
        </div>
    </div>
</div>